filter:
    excluded_paths: [test/*, example/*]

checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_cs_fixer: true
    php_code_sniffer: true
    php_cpd: true
    php_hhvm: true
    php_mess_detector: true
    php_analyzer: true
    php_pdepend: true
    sensiolabs_security_checker: true
