language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update || true
  - composer --prefer-source --dev install

script:
  - vendor/bin/phpunit --debug --coverage-clover=coverage.clover

sudo: false

services:
  - memcached
