language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update || true
  - composer --prefer-source --dev install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

sudo: false

services:
  - memcached
